
services:
  db:
    image: postgres:latest  # or mysql, mongo, etc.
    container_name: db
    environment:
      POSTGRES_DB: "tr_db"
      POSTGRES_USER: "reda_user"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reda_user -d tr_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
  backend:
    build: ./backend  # Path to your Django backend Dockerfile
    container_name: backend
    restart: always
    environment:
      POSTGRES_DB: "tr_db"
      POSTGRES_USER: "reda_user"
      POSTGRES_PASSWORD: "123"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"  # Maps port 8000 on the host to the backend
    networks:
      - app-network
    volumes:
      - ./backend:/app/  # Mounts the backend directory to the Django container

  frontend:
    build: ./frontend  # Path to your frontend Dockerfile, which should copy static files to nginx
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8080:8080"  # Maps port 80 on the host to the frontend service (nginx)
    networks:
      - app-network
    volumes:
      - ./frontend:/var/www/html  # Mounts the frontend directory to the nginx container
networks:
  app-network:
    driver: bridge