# Generated by Django 5.1.5 on 2025-02-01 00:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_name", models.CharField(max_length=255)),
                ("player1_username", models.CharField(max_length=255)),
                ("player2_username", models.CharField(max_length=255)),
                ("player1_score", models.IntegerField()),
                ("player2_score", models.IntegerField()),
                ("winner", models.CharField(max_length=255)),
                ("game_type", models.CharField(max_length=50)),
                (
                    "tournament_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "transaction_hash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "game_scores",
            },
        ),
    ]
