# Generated by Django 5.1.5 on 2025-01-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_intra42user_options_alter_intra42user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intra42user',
            name='image',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
    ]
